SD_COMMENT="This is for local development"
APP_SECRET_KEY="ASKASK"
JWT_SECRET="JWTSECRET"
POSTGRES_PASSWORD="thispasswordisverysecure"
BASEUSER_PW="basepw"
BASEEDITOR_PW="editorpw"
BASEADMIN_PW="basepw"
DROPBOX_APP="DBAPPPW"

SALESFORCE_USERNAME=''
SALESFORCE_CONSUMER_KEY=''
SALESFORCE_DOMAIN=''
TENANT_ID=''
INSTANCE_URL=''
CREATOR_CONTACT_ID=''
