apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: \temp\kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: \temp\kompose -f docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: \temp\kompose -f docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: development
          image: localhost:5000/src-server:latest
          imagePullPolicy: ""
          name: paws-compose-server
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /app/static/raw_data
              name: src-archive
      restartPolicy: Always
      serviceAccountName: ""
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: src-archive
          persistentVolumeClaim:
            claimName: src-archive
status: {}
