"""postgres matching

Revision ID: 45a668fa6325
Revises: fc7325372396
Create Date: 2022-02-10 16:19:13.283250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45a668fa6325'
down_revision = 'fc7325372396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_matches',
    sa.Column('source_type_1', sa.String(), nullable=False),
    sa.Column('source_id_1', sa.String(), nullable=False),
    sa.Column('source_type_2', sa.String(), nullable=False),
    sa.Column('source_id_2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('source_type_1', 'source_id_1', 'source_type_2', 'source_id_2')
    )
    op.create_table('salesforcecontacts',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('mailing_country', sa.String(), nullable=True),
    sa.Column('mailing_street', sa.String(), nullable=True),
    sa.Column('mailing_city', sa.String(), nullable=True),
    sa.Column('mailing_state_province', sa.String(), nullable=True),
    sa.Column('mailing_zip_postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('shelterluvpeople',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('internal_id', sa.String(), nullable=True),
    sa.Column('associated', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('apartment', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('animal_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('volgistics',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('complete_address', sa.String(), nullable=True),
    sa.Column('street_1', sa.String(), nullable=True),
    sa.Column('street_2', sa.String(), nullable=True),
    sa.Column('street_3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('all_phone_numbers', sa.String(), nullable=True),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('work', sa.String(), nullable=True),
    sa.Column('cell', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index('idx_pdp_contacts_source_type_and_id', 'pdp_contacts', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_pdp_contacts_mobile'), 'pdp_contacts', ['mobile'], unique=False)
    op.create_index(op.f('idx_pdp_contacts_lower_first_name'), 'pdp_contacts', [sa.text('lower(first_name)')], unique=False)
    op.create_index(op.f('idx_pdp_contacts_lower_last_name'), 'pdp_contacts', [sa.text('lower(last_name)')], unique=False)
    op.create_index(op.f('idx_pdp_contacts_lower_email'), 'pdp_contacts', [sa.text('lower(email)')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdp_contacts_lower_email'), table_name='pdp_contacts')
    op.drop_index(op.f('ix_pdp_contacts_lower_last_name'), table_name='pdp_contacts')
    op.drop_index(op.f('ix_pdp_contacts_lower_first_name'), table_name='pdp_contacts')
    op.drop_index(op.f('ix_pdp_contacts_mobile'), table_name='pdp_contacts')
    op.drop_index('idx_pdp_contacts_source_type_and_id', table_name='pdp_contacts')
    op.drop_table('volgistics')
    op.drop_table('shelterluvpeople')
    op.drop_table('salesforcecontacts')
    op.drop_table('manual_matches')
    # ### end Alembic commands ###
