version: '3.7'

services:
  db:
    container_name: paws-compose-db
    ports:
      - "5432:5432"
    image: postgres:11.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: thispasswordisverysecure
      POSTGRES_DB: paws

  server:
    container_name: paws-compose-server
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - src_archive:/app/static/raw_data

    environment:
      - FLASK_ENV=development

  client:
    build: ./client
    container_name: paws-compose-client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PAWS_API_HOST=paws-compose-server
    stdin_open: true


#using named volumes fixs a windows docker bug relating to container permissions
#https://stackoverflow.com/questions/49148754/docker-container-shuts-down-giving-data-directory-has-wrong-ownership-error-wh
volumes:
  postgres:
  src_archive:
